### ISSUE TITLE
AutoPricing Stop

### ISSUE THREAD

**Issue by deMorphine** [Unovamata/AutoBuyerPlus#10]
After clicking Start AutoPricing, it will go through the list until the last item and stops:

https://i.imgur.com/Q9IAcH6.png

If I go back to the Options page to check what happened, it will say "Status: Searching ..."

https://i.imgur.com/f3HipKw.png

**Comment by Unovamata** [comment]
Do you have the Auto Price Submit option active? Can you submit the prices manually?

**Comment by deMorphine** [comment]
Yes I have that option active. After the freezing on the last item, I will go back and Cancel Pricing, and can Submit them manually.

**Comment by Unovamata** [comment]
Can you send me your Settings Presets via Discord to the user "ZenAkiSen". This way I can replicate your environment 1:1 and fix the issue you are facing faster.

Thank you for your time and effort. 🙇🏻

**Comment by Unovamata** [comment]
This issue was related to the way the extension handled list indexes, causing some null references when the AutoPricer finished pricing items. This issue has been fixed.

Thank you for your report and time. 🙇🏻
