### ISSUE TITLE
Bug in the attic

### ISSUE THREAD

**Issue by galfink** [Unovamata/AutoBuyerPlus#11]
When i put the last reestock around 7am, the next restock ranges move to more than 1 hour before.

![image](https://github.com/user-attachments/assets/e941ab58-3254-4b0b-be8c-af2a34160f67)

**Comment by Unovamata** [comment]
The AutoAttic process won't be fixed until the next major version release. Sorry for letting you down. 🙇🏻 

I hope you look forward to version 0.8v.
