### ISSUE TITLE
Not returning to shop after purchase/not going to the next shop (experimental version)

### ISSUE THREAD

**Issue by baottousai** [Unovamata/AutoBuyerPlus#12]
https://i.imgur.com/LQIezDi.png
https://i.imgur.com/IhxYZ6K.png
AB was not returning to the shop after purchasing item
when manually going back to the shop, AB would not go to the next shop in rotation. instead, it would keep refreshing the same shop.

**Comment by Unovamata** [comment]
Have you added the shops you want to cycle to, to the "Shop Configuration" menu? For the shops to cycle, you have to be in one of the shops of your list and then the AutoBuyer will cycle through them. If you're not in a shop in your cycle list, the AutoBuyer will stick to the currently loaded shop as it will assume you want to restock that shop specifically.

Sorry if this is not as clear, considering this is the experimental version, some features need to be thoroughly explained and documented once the actual "Long Term Support" version releases. Thank you for your understanding.

Please keep me updated on this topic. 🙇🏻 

![image](https://github.com/user-attachments/assets/b5cb37a8-b44a-42be-ac5b-7952e43f2ddf)

**Comment by Unovamata** [comment]
As for the not returning to the main shop after a purchase. I have not heard about that issue before. I'll dig into why is causing this problem. 

Do you have the "Move Haggling Processes to New Tabs" option active?

**Comment by baottousai** [comment]
yes i do have a list of shops. maybe at the time i was in a shop that wasn't on a list but i'm not sure. but i am still seeing it not return to the shop after buying an item. i'm not using the new tab option.

**Comment by Unovamata** [comment]
Usually, the AutoHaggler returns to the shop after roughly 5 seconds after a purchase. Have you waited 5 seconds or so to see if the AutoHaggler returns to the shop in question? This measure is set to counteract with "Five Second Rule" issues.

Can you also test this further so I can reproduce it on my end? Thank you. 🙇🏻

**Comment by Unovamata** [comment]
I have been able to isolate the issue. It seems that this only occurred whenever an installation of AutoBuyer+ did not use the "Move Haggling Processes to New Tabs". I will push another experimental update in the following days, please confirm if this issue has been fixed by then.

Thank you very much!
