### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by nikoctober** [Unovamata/AutoBuyerPlus#13]
stack:TypeError: Failed to fetch at FetchLatestGitHubVersion (chrome-extension://kldbaafoefdbglaahbmhhhiihkpkgpnl/src/background.js:193:36) at CheckVersionWhenBackgroundActive (chrome-extension://kldbaafoefdbglaahbmhhhiihkpkgpnl/src/background.js:159:37) at chrome-extension://kldbaafoefdbglaahbmhhhiihkpkgpnl/src/background.js:273:1:get=function () { [native code] },set=function () { [native code] },enumerable=false,configurable=true,message:Failed to fetch:value=Failed to fetch,writable=true,enumerable=false,configurable=true,

Thank you for your attention to this matter.

**Comment by Unovamata** [comment]
This issue is caused because the extension could not ping the version check server. This usually happens in some first installs or if the user has an unstable internet connection while using the extension.

Thank you for your report.
