### ISSUE TITLE
Cannot install extension

### ISSUE THREAD

**Issue by Nickwarlick** [Unovamata/AutoBuyerPlus#2]
when i try to unpack the extension i get this,

Failed to load extension
File
~/Desktop/AutoBuyerPlus-0.7.26.41v 2/Autobuyer
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by Unovamata** [comment]
It seems you are not selecting the extension's folder correctly. To install AutoBuyer+ you must select the folder where the "manifest.json" file is present. 

![image](https://github.com/Unovamata/AutoBuyerPlus/assets/91705840/1bddc4aa-d5e6-4b6e-a0ce-f295a27b3ecb)
