### ISSUE TITLE
Having troubles when using NeoBuyer+ if using VPN

### ISSUE THREAD

**Issue by NS157** [Unovamata/AutoBuyerPlus#4]
I don't know why but when I use VPN, it sometimes show up this, but it has no problems before the last two updates.
![未命名](https://github.com/Unovamata/AutoBuyerPlus/assets/172095334/80926043-8246-4ce3-8e37-cd90b48f0eea)

**Comment by Unovamata** [comment]
Hello NS157. Thank you for your report. I did not know that VPNs conflicted with the extension. I am very sorry for this inconvenience. I will look into the source of this issue.

Thank you for supporting AutoBuyer+. I hope you continue to utilize the extension in the foreseeable future.

**Comment by Unovamata** [comment]
If you can confirm to me if you can access this site it would be amazing:

https://api.github.com/repos/Unovamata/AutoBuyerPlus/releases/latest

**Comment by NS157** [comment]
I could see some code when I click the link above, is that what you mean access the site?

**Comment by NS157** [comment]
Oh, I see this error 
stack:TypeError: Failed to fetch at FetchLatestGitHubVersion (chrome-extension://iebfjpjecjpgamapjbbjapfdfahjchig/src/bg/background.js:179:36) at CheckVersionWhenBackgroundActive (chrome-extension://iebfjpjecjpgamapjbbjapfdfahjchig/src/bg/background.js:145:37) at chrome-extension://iebfjpjecjpgamapjbbjapfdfahjchig/src/bg/background.js:224:1:get=function () { [native code] },set=function () { [native code] },enumerable=false,configurable=true,message:Failed to fetch:value=Failed to fetch,writable=true,enumerable=false,configurable=true,

**Comment by Unovamata** [comment]
Yes! Can you send me a screenshot of what you see in the page?

I think that your VPN or Github are blocking your requests to Github's API. Have you tried with other VPN providers? This seems to be a common problem with the snippet of code used for this update check along with VPNs.

Try getting a VPN with a DNS, that may solve the problem.

**Comment by NS157** [comment]
So how could I see if my VPN with a DNS?

**Comment by NS157** [comment]
![未命名](https://github.com/Unovamata/AutoBuyerPlus/assets/172095334/292df5f9-1fe5-4313-bf82-2bf95dd0ee55)
This is what I see when I click the link you guves above

**Comment by Unovamata** [comment]
You would have to contact with your VPN provider to know if they have a DNS.

Regardless, the screenshot you sent is extremely helpful! I will read the information attached to that link to help you with your issue.

I am very sorry for this inconvenience since I have never tested this use case, so thank you for taking the time for testing this thoroughly. I will report any milestones I encounter.

Thank you for your continuous support!

**Comment by Unovamata** [comment]
Can you confirm me if you can access this Github page?

https://github.com/Unovamata/AutoBuyerPlus/tags

It should look like this:

![image](https://github.com/Unovamata/AutoBuyerPlus/assets/91705840/99863286-97bb-4913-9d73-56c5648f888c)

**Comment by NS157** [comment]
Yes I could and it's the same as your photo

**Comment by Unovamata** [comment]
Perfect! I will try to issue a fix for your problem either today or in the following days.

Thank you for using AutoBuyer+!

**Comment by Unovamata** [comment]
This has been fixed in the latest commit. Please wait patiently for the next update.

If you encounter any bugs please reopen this issue. Thank you very much for your report and I hope you continue using AutoBuyer+ for the foreseeable future. 🙇🏻

**Comment by Unovamata** [comment]
Thank you for your patience, the new version 0.7.27.47v has been released. Please test if this issue has been solved successfully.
