### ISSUE TITLE
Fetch Version Error

### ISSUE THREAD

**Issue by Unovamata** [Unovamata/AutoBuyerPlus#5]
Hello! Not sure if this is the right place to post, but I kept encountering this error for the past few days even though it is the latest version.

stack:TypeError: Failed to fetch at FetchLatestGitHubVersion (chrome-extension://fkpelamfojecfepefbdpkalokicmnecm/src/bg/background.js:187:36) at CheckVersionWhenBackgroundActive (chrome-extension://fkpelamfojecfepefbdpkalokicmnecm/src/bg/background.js:153:37) at chrome-extension://fkpelamfojecfepefbdpkalokicmnecm/src/bg/background.js:265:1:get=function () { [native code] },set=function () { [native code] },enumerable=false,configurable=true,message:Failed to fetch:value=Failed to fetch,writable=true,enumerable=false,configurable=true,

_Originally posted by @Kakashixy in https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/issues/10#issuecomment-2176116631_

**Comment by Unovamata** [comment]
@Kakashixy Are you using the latest version from this repository?

**Comment by Kakashixy** [comment]
Mine is currently version 0.7.27.47 which I believe is the latest version?
After this error is triggered, it works again after a while (e.g., reload the extension or mass refresh or disabling -> reload -> mass refresh) but it gets triggered again at random?

**Comment by Unovamata** [comment]
Do you have a stable internet connection? Are you using a VPN or anything that may slow your internet connection?

The extension needs to be online at all times for security and account protection measures. Usually when you reload, the extension will check the current version again.

**Comment by Kakashixy** [comment]
Yes, I have a stable internet connection. Am using VPN which might be the cause.
Thanks for checking on this. :)
