### ISSUE TITLE
AB+ is not loading time/date of the shifts since last update in volunteer page

### ISSUE THREAD

**Issue by GomaSama1313** [Unovamata/AutoBuyerPlus#7]
![AB+](https://github.com/user-attachments/assets/c35b44b5-9b40-44a0-a148-35b2169cef16)

**Comment by Unovamata** [comment]
Thank you for your report! This has been fixed in the latest version of the extension.

The problem resided in the volunteering page because of some recent changes TNT did to the volunteering shifts. I am very sorry for this inconvenience. Thank you for using AutoBuyer+.
