### ISSUE TITLE
AutoPricer Stuck After Searching in SW

### ISSUE THREAD

**Issue by deMorphine** [Unovamata/AutoBuyerPlus#8]
Hi, AutoPricer does the expected 3-5 SW searches set in the options, but then gets stuck on the SW results page. 

I click on Load Shop Inventory then Start AutoPricing and the new page opens doing the 3-5 searches.

When I go check the extension Options, it says it is still searching for the item:
https://i.imgur.com/sKt444u.png

Here is the development console log:
https://i.imgur.com/dHZtQiU.png

**Comment by deMorphine** [comment]
Same issue still where AutoPricing stops after doing some searches, but this time I ticked "Check Unpriced" in the options. 

Here is the development console log:
https://imgur.com/9nGgJKI

**Comment by Unovamata** [comment]
This has been fixed in the latest experimental version. I will deploy this change in the Long-term Support version of the extension. Thank you for all your reports. 🙇🏻
