### ISSUE TITLE
Autobuyer+ not working

### ISSUE THREAD

**Issue by BatDaddyxX** [Unovamata/AutoBuyerPlus#9]
I've downloaded everything needed for this, changed browsers to Opera GX as recommended and the ext. Site doesn't not allow me to scroll or select anything just as the video provided on Discord shown by XxBatDadxX

**Comment by Unovamata** [comment]
It seems this issue is a hardware related problem. Thank you for your report, I hope you test out the new GUI in version 0.8v.
